### ISSUE TITLE
build fails with icecream-master

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icemon#30]
I just built icemon 3.1.0 with icecream-master and the build fails with some linker errors.

I added the following to src/CMakeLists.txt as a work around

    FIND_LIBRARY(LZO_LIBRARIES NAMES lzo2)
    FIND_LIBRARY(CAP_LIBRARIES NAMES cap-ng)

And then to target_link_libraries
        ${LZO_LIBRARIES}
        ${CAP_LIBRARIES}

This of course not the correct fix, but I'm not clear on what is correct. Obviously you want to build with older versions of icecream, which don't need these libraries and thus they might not even be installed.

I'm hoping to release icecream 1.1 in a month or so, and I feel like we should have a solution to this.

**Comment by krf** [comment]
The `FindIcecream.cmake` I wrote should figure this out on its own. Please check out: https://github.com/icecc/icemon/blob/master/cmake/modules/FindIcecream.cmake#L29

Maybe you just need to remove the `CMakeCache.txt` to force CMake re-detecting the libraries icecc requires?

**Comment by HenryMiller1** [comment]
I didn't have pkgconf installed, which is an optional package so cmake completed with no errors.  Only a line hidden in the middle clued me into this.

I think your readme should include
    sudo apt-get install pkgconf 
maybe pkgconf should not be optional in cmake?

This can be closed if you don't want to take action.

**Comment by krf** [comment]
True, I've now marked it as required. That should be enough.

Thanks!
