### ISSUE TITLE
a host with many clusters (networks that scheduler runs on)

### ISSUE THREAD

**Issue by tcloaa** [icecc/icemon#31]
When I use icemon, it shows that clusters that I am not interested in (which is different from NETNAME in ` /etc/icecc/icecc.conf`.

```
scheduler is on 192.168.168.254:8765 (net ICECREAM)
```
This scheduler isn't the one I wanna play with.

How can I change conf of icemon to focus the network that I am actually interested in?

Thanks,

**Comment by krf** [comment]
Two possibilities: You can set the netname via ...

a) command-line parameters, i.e. `icemon -netname MY_NETNAME` (since v3.1.0)
b) environment variables, i.e.: `USE_SCHEDULER=MY_NETNAME icemon`

**Comment by tcloaa** [comment]
yeah, just not find this information in any doc...

thx
