### ISSUE TITLE
investigate codacy 

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icemon#35]
As an admin for the icecc organization I enabled codacy checks in this repository. However I do not otherwise contribute to this project and so I cannot state with certainty that this is tool provides anything useful.

https://www.codacy.com/app/icecc/icemon/dashboard

Consider putting a badge someplace visible if this is considered useful. 

Alternatively I can delete these checks.

**Comment by krf** [comment]
Fixed some issues:
  https://github.com/icecc/icemon/commit/5a85427b0daed0bb92dc6d3f379ccdb4921fb8f2

I don't think I have permissions to create/view badges(?). Tried to follow https://support.codacy.com/hc/en-us/articles/212799365-Badges but there's no link to "Settings".

**Comment by llunak** [comment]
This has been handled AFAICT.
