### ISSUE TITLE
Request: Release a new version

### ISSUE THREAD

**Issue by gojpdchx** [icecc/icemon#42]
Version 1.2 of `icecream` has been released, and d71e595 is needed for proper scheduler discovery, so I believe that it will be a good idea to release a new version containing the fix.

**Comment by HenryMiller1** [comment]
We need the news file updated before we can do a release. We also need
some good testing to make sure that there are no other bugs. You could
help out with either of these.
I'll try to remember to do a release when I get back from vacation (us
holiday) and have access to a good computer. Or maybe someone else will
step in (or give a good reason not to release)


On Thu, Nov 22, 2018, at 10:33 PM, gojpdchx wrote:
> Version 1.2 of icecream has been released, and d71e595 is needed for
> proper scheduler discovery, so I believe that it will be a good idea
> to release a new version containing the fix.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Links:

  1. https://github.com/icecc/icemon/issues/42

**Comment by HenryMiller1** [comment]
Looks like your requested commit is in 1.2. Did you mean this message
for a distribution to package 1.2, or am I missing something?


On Thu, Nov 22, 2018, at 10:33 PM, gojpdchx wrote:
> Version 1.2 of icecream has been released, and d71e595 is needed for
> proper scheduler discovery, so I believe that it will be a good idea
> to release a new version containing the fix.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
Links:

  1. https://github.com/icecc/icemon/issues/42

**Comment by gojpdchx** [comment]
@HenryMiller1 
Sorry for my late reply.
If I use the latest version of icecream (i.e. Version 1.2) with the latest version of icemon (i.e. Version 3.1.0), then icemon will fail to find the scheduler.  #40 fixed the problem, but icemon 3.1.0 does not include this fix.

**Comment by krf** [comment]
Done:

commit 6b120f3ea8393b89f446446bc26eaf8c5f765bb1 (HEAD -> master, tag: v3.2.0, origin/master, origin/HEAD)
Author: Kevin Funk <kfunk@kde.org>
Date:   Mon Dec 10 10:03:52 2018 +0100

    Prepare for 3.2.0 release

**Comment by gojpdchx** [comment]
@krf 
Thanks!
Could you please tag the new version so that users can notice the the release of v3.2.0 on GitHub (https://github.com/icecc/icemon/releases)?
