### ISSUE TITLE
Conflict with iceccd

### ISSUE THREAD

**Issue by stayprivate** [icecc/icemon#48]
Using 1.2 of icecream and 3.2 of icemon, which I built myself.

I have been chasing some communication issue, broken pipe as seen from the scheduler.  

I'm still not 100% sure about this but it seems that if iceccd and icemon are running on the the same machine, the scheduler (which is also on the same machine for now ) get confused about the two. I might restart icemon and sometimes it won't see the scheduler, never, sometime the same thing happens with iceccd.

In case it matters, I'm forcing ip with -s for iceccd and monitor. Using -n as well  for iceccd and icecd-scheduler.  

Should this work ?

**Comment by llunak** [comment]
Yes, it should work (and it does here). If you want to debug this further, you can set ICECC_DEBUG=debug for icemon and pass -v (or even better rather -v -v -v) to iceccd and icecc-scheduler.

**Comment by llunak** [comment]
No response, closing.
