### ISSUE TITLE
read icecream.conf to find scheduler

### ISSUE THREAD

**Issue by milianw** [icecc/icemon#49]
the scheduler cannot be found on my setup (vpn with firewall), I have to explicitly set the scheduler host through `/etc/icecream.conf`. Sadly, icemon doesn't look at that file, and thus my `ICECREAM_SCHEDULER_HOST` setting isn't picked up automatically. I have to pass that manually every time I start `icemon`, which is annoying :)

**Comment by HenryMiller1** [comment]
Icecream.conf is a distribution provided file. Icecream and icemon do not read it. 

-- 
 Henry Miller
 hank@millerfarm.com

**Comment by milianw** [comment]
ah, a pity! I'll stick to my `alias` then to hardcode the scheduler.
