### ISSUE TITLE
Can not visualize setup with more then one scheduler

### ISSUE THREAD

**Issue by nierob** [icecc/icemon#50]
Icecc documentation says that it is re-commanded to have many schedulers in the network (https://github.com/icecc/icecream#some-advice-on-configuration). Such setup works well, but it is hard to monitor it by icemon, because one instance of it shows state of only one scheduler. It is very limiting especially in dynamic setup in which schedulers can be connected and disconnected randomly from the network, therefore --scheduler command line switch can not be used.

**Comment by llunak** [comment]
The documentation also says that the cluster will automatically decide on one master scheduler which will be used. So it is enough to monitor that scheduler, and Icemon will by default connect to that scheduler, just like all nodes do.
