### ISSUE TITLE
[Feature request] Discover all schedulers on the network, connect to the one currently used

### ISSUE THREAD

**Issue by torokati44** [icecc/icemon#59]
It would be really nice if Icemon could somehow determine which scheduler is the locally running iceccd daemon currently connected to, and then connected to the same scheduler automatically.

At the moment it is somewhat misleading when the scheduler currently being used by all machines on the network (the "master") is not on the computer I'm using, and Icemon shows zero connected hosts, even though distributed compilation actually works. There is also no trivial way to find out the current "master" scheduler - maybe by checking the logs of iceccd.

Viewing the network is often helpful, for example check the number of cores available, which is needed to determine the number of parallel compilation jobs one should start (the -j argument of make for example). At least until something like https://github.com/icecc/icecream/issues/85 is in place.

What would be even better, is if it listed all the available schedulers on the network, discovered by broadcast messages (similarly how iceccd also does it), and would let the user select the one to inspect, and switch between them, from a menu.

**Comment by llunak** [comment]
Icemon generally should connect to the same scheduler, it even uses the same code for that. I assume you ask for this as a workaround for https://github.com/icecc/icecream/issues/521 ? One one network there shouldn't be more than one active scheduler for one hostname.

**Comment by torokati44** [comment]
You are right, now that I applied the ~~fix~~ __workaround__ for icecc/icecream#521 on my firewall, icemon works as expected as well. Sorry for the issue noise.

**Comment by torokati44** [comment]
Although it would still be "nice" to be able to browse and select from all the discovered schedulers (for example, to easier notice and debug issues like icecc/icecream#521), but it's probably not worth it, since "normally", if (and when) everything works fine, only one scheduler on the network is of interest.
